ISLANDGAME_SIERRA_DESERT_MapScripts::
# 2 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, ISLANDGAME_SIERRA_DESERT_MapScripts_MAP_SCRIPT_ON_LOAD
	.byte 0

ISLANDGAME_SIERRA_DESERT_MapScripts_MAP_SCRIPT_ON_LOAD:
# 3 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_init
# 4 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_addspace 1, 1, 18, 12
# 5 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_spawn 8, 19, 12, 22
# 6 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_spawn 4, 19, 6, 22
# 7 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_spawn 16, 21, 18, 22
# 8 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_spawn 1, 19, 2, 20
# 9 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_spawn 1, 19, 2, 20
# 10 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_spawn 1, 19, 2, 20
# 11 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_spawn 1, 22, 1, 22
# 12 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_spawn 1, 22, 1, 22
# 13 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_spawn 1, 22, 1, 22
# 14 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_spawn 1, 22, 1, 22
# 15 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_spawn 1, 22, 1, 22
# 16 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_spawn 1, 22, 1, 22
# 17 "data/maps/ISLANDGAME_SIERRA_DESERT/scripts.pory"
	mapgen_spawn 1, 22, 1, 22
	return

