ISLANDGAME_AETHERIA_CONDO_3F_MapScripts::
	.byte 0


ISLANDGAME_AETHERIA_CONDO_3F_Officer::
# 5 "data/maps/ISLANDGAME_AETHERIA_CONDO_3F/scripts.pory"
	lock
# 6 "data/maps/ISLANDGAME_AETHERIA_CONDO_3F/scripts.pory"
	faceplayer
# 7 "data/maps/ISLANDGAME_AETHERIA_CONDO_3F/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_CONDO_3F_Officer_Text_0, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_CONDO_3F_OldMan::
# 13 "data/maps/ISLANDGAME_AETHERIA_CONDO_3F/scripts.pory"
	lock
# 14 "data/maps/ISLANDGAME_AETHERIA_CONDO_3F/scripts.pory"
	faceplayer
# 15 "data/maps/ISLANDGAME_AETHERIA_CONDO_3F/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_CONDO_3F_OldMan_Text_0, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_CONDO_3F_Officer_Text_0:
# 8 "data/maps/ISLANDGAME_AETHERIA_CONDO_3F/scripts.pory"
	.string "Move along! There's nothing to see\n"
	.string "here! We're busy doing grown-up stuff!$"

ISLANDGAME_AETHERIA_CONDO_3F_OldMan_Text_0:
# 16 "data/maps/ISLANDGAME_AETHERIA_CONDO_3F/scripts.pory"
	.string "There is nothing more frightening than\n"
	.string "finding out that your next door\l"
	.string "neighbors have been using their room as\l"
	.string "an criminal hideout all this time...\p"
	.string "I thought they were nice young\n"
	.string "gentlemen... but after overhearing one\l"
	.string "of the detectives, they might be\l"
	.string "members of an underground syndicate?\p"
	.string "Ooooh, what could've strayed these\n"
	.string "young lads down this dark path?$"
