#ifndef GUARD_CONSTANTS_ISLANDGAME_H
#define GUARD_CONSTANTS_ISLANDGAME_H

// VAR_MINTY_MEADOWS_STATE
#define MINTY_MEADOWS_BATTLING_RIVAL 0
#define MINTY_MEADOWS_SEARCHING_FOR_MAREEP 1
#define MINTY_MEADOWS_BATTLING_MIGHTYENA 2
#define MINTY_MEADOWS_SAVED_MAREEP 3

// VAR_CAMP_PERSI_STATE
#define CAMP_PERSI_SEARCHING_FOR_CLUES 0
#define CAMP_PERSI_SEARCHING_FOR_CARD 1
#define CAMP_PERSI_DEFEATED_LOSER 2
#define CAMP_PERSI_CLAIMED_LOSER_REWARD 3

#endif // GUARD_CONSTANTS_ISLANDGAME_H
