#ifndef GUARD_CONSTANTS_ISLANDGAME_H
#define GUARD_CONSTANTS_ISLANDGAME_H

// VAR_MINTY_MEADOWS_STATE
#define MINTY_MEADOWS_BATTLING_RIVAL 0
#define MINTY_MEADOWS_SEARCHING_FOR_MAREEP 1
#define MINTY_MEADOWS_BATTLING_MIGHTYENA 2
#define MINTY_MEADOWS_SAVED_MAREEP 3

#endif // GUARD_CONSTANTS_ISLANDGAME_H
