ISLANDGAME_ORANNA_CHERIPORT_HOUSE1_MapScripts::
	.byte 0


ISLANDGAME_ORANNA_CHERIPORT_HOUSE1_NPC1::
# 5 "data/maps/ISLANDGAME_ORANNA_CHERIPORT_HOUSE1/scripts.pory"
	lock
# 6 "data/maps/ISLANDGAME_ORANNA_CHERIPORT_HOUSE1/scripts.pory"
	faceplayer
# 7 "data/maps/ISLANDGAME_ORANNA_CHERIPORT_HOUSE1/scripts.pory"
	msgbox ISLANDGAME_ORANNA_CHERIPORT_HOUSE1_NPC1_Text_0
# 11 "data/maps/ISLANDGAME_ORANNA_CHERIPORT_HOUSE1/scripts.pory"
	closemessage
# 12 "data/maps/ISLANDGAME_ORANNA_CHERIPORT_HOUSE1/scripts.pory"
	release
	return


ISLANDGAME_ORANNA_CHERIPORT_HOUSE1_NPC2::
# 18 "data/maps/ISLANDGAME_ORANNA_CHERIPORT_HOUSE1/scripts.pory"
	lock
# 19 "data/maps/ISLANDGAME_ORANNA_CHERIPORT_HOUSE1/scripts.pory"
	faceplayer
# 20 "data/maps/ISLANDGAME_ORANNA_CHERIPORT_HOUSE1/scripts.pory"
	msgbox ISLANDGAME_ORANNA_CHERIPORT_HOUSE1_NPC2_Text_0
# 25 "data/maps/ISLANDGAME_ORANNA_CHERIPORT_HOUSE1/scripts.pory"
	release
	return


ISLANDGAME_ORANNA_CHERIPORT_HOUSE1_NPC1_Text_0:
# 8 "data/maps/ISLANDGAME_ORANNA_CHERIPORT_HOUSE1/scripts.pory"
	.string "Marya has really become a hot tourist\n"
	.string "destination in recent years!\p"
	.string "It's interesting seeing so many people\n"
	.string "from different regions visiting here!$"

ISLANDGAME_ORANNA_CHERIPORT_HOUSE1_NPC2_Text_0:
# 21 "data/maps/ISLANDGAME_ORANNA_CHERIPORT_HOUSE1/scripts.pory"
	.string "Oranna is home to one of Marya's\n"
	.string "legendary Isle Guardians.\p"
	.string "The mythical Wings of Frost: Articuno!\p"
	.string "With a single flap of its wings, it can\n"
	.string "chill the moisture in the air around it,\l"
	.string "creating snow even in the sweltering\l"
	.string "tropics of Marya!$"
