ISLANDGAME_AETHERIA_CONDO_2F_ROOM1_2_MapScripts::
	.byte 0


ISLANDGAME_AETHERIA_CONDO_2F_ROOM1_2_Man::
# 5 "data/maps/ISLANDGAME_AETHERIA_CONDO_2F_ROOM1_2/scripts.pory"
	lock
# 6 "data/maps/ISLANDGAME_AETHERIA_CONDO_2F_ROOM1_2/scripts.pory"
	faceplayer
# 7 "data/maps/ISLANDGAME_AETHERIA_CONDO_2F_ROOM1_2/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_CONDO_2F_ROOM1_2_Man_Text_0, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_CONDO_2F_ROOM1_2_Gameboy::
# 14 "data/maps/ISLANDGAME_AETHERIA_CONDO_2F_ROOM1_2/scripts.pory"
	lock
# 15 "data/maps/ISLANDGAME_AETHERIA_CONDO_2F_ROOM1_2/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_CONDO_2F_ROOM1_2_Gameboy_Text_0, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_CONDO_2F_ROOM1_2_Man_Text_0:
# 8 "data/maps/ISLANDGAME_AETHERIA_CONDO_2F_ROOM1_2/scripts.pory"
	.string "I can't believe I'm paying ¥20,000 a day\n"
	.string "just to stay in this dinky little room...\p"
	.string "Everything here is so much smaller in\n"
	.string "comparison to Unova.$"

ISLANDGAME_AETHERIA_CONDO_2F_ROOM1_2_Gameboy_Text_0:
# 16 "data/maps/ISLANDGAME_AETHERIA_CONDO_2F_ROOM1_2/scripts.pory"
	.string "Go away! Can't you see I'm busy\n"
	.string "sweeping these dirty Uber abusers?\p"
	.string "Imagine losing with a team of six\n"
	.string "legendaries. Couldn't be me!$"
