ISLANDGAME_AETHERIA_CARD_STORE_MapScripts::
	.byte 0


ISLANDGAME_AETHERIA_CARD_STORE_SaltyPlayer::
# 6 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	lock
# 7 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_CARD_STORE_SaltyPlayer_Text_0, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_CARD_STORE_LittleCamper::
# 15 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	lock
# 16 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_CARD_STORE_LittleCamper_Text_0, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_CARD_STORE_Nerd::
# 22 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	lock
# 23 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_CARD_STORE_Nerd_Text_0, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_CARD_STORE_Girl::
# 30 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	lock
# 31 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_CARD_STORE_Girl_Text_0, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_CARD_STORE_AlakazamPlayer::
# 37 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	lock
# 38 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_CARD_STORE_AlakazamPlayer_Text_0, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_CARD_STORE_Whiner::
# 46 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	lock
# 47 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_CARD_STORE_Whiner_Text_0, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_CARD_STORE_SaltyPlayer_Text_0:
# 8 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	.string "Woooow, who could've guessed, another\n"
	.string "lame ass Crustle player ruining the\l"
	.string "game for everyone as usual.\p"
	.string "Can they just ban that card already?\n"
	.string "Like are we for real, man? It's just not\l"
	.string "fair anymore dude like I can't do\l"
	.string "anything about it.\p"
	.string "I didn't pay ¥15000 just to lose to some\n"
	.string "kid with his degenerate glue-eater\l"
	.string "stun deck!$"

ISLANDGAME_AETHERIA_CARD_STORE_LittleCamper_Text_0:
# 17 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	.string "Ummmmm, good game...?$"

ISLANDGAME_AETHERIA_CARD_STORE_Nerd_Text_0:
# 24 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	.string "You know... if you're looking to get\n"
	.string "better, we could continue playing at my\l"
	.string "place...\p"
	.string "I'd be happy to teach you some\n"
	.string "deckbuilding quantum mechanics...$"

ISLANDGAME_AETHERIA_CARD_STORE_Girl_Text_0:
# 32 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	.string "Eeeeeh...$"

ISLANDGAME_AETHERIA_CARD_STORE_AlakazamPlayer_Text_0:
# 39 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	.string "Evolve Abra into Kadabra. Use Kadabra\n"
	.string "ability to draw 2 cards. Evolve\l"
	.string "Dunsparce into Dudunsparce. Attach\l"
	.string "Enriching Energy to Dudunsparce to\l"
	.string "draw 4 cards.\p"
	.string "Use Dudunsparce ability, draw 3 cards\n"
	.string "and shuffle back. Play Poké Pad to add\l"
	.string "Alakazam. Use Rare Candy to evolve Abra\l"
	.string "into Alakazam. Use Alakazam ability to\l"
	.string "draw 3 cards.\p"
	.string "Use Wondrous Patch to attach a Psychic\n"
	.string "Energy to Alakazam. Use my other\l"
	.string "Dudunsparce ability to draw 3 cards and\l"
	.string "shuffle it back. Use Fezandipiti ability\l"
	.string "to draw 3 more cards...$"

ISLANDGAME_AETHERIA_CARD_STORE_Whiner_Text_0:
# 48 "data/maps/ISLANDGAME_AETHERIA_CARD_STORE/scripts.pory"
	.string "DOES YOUR TURN HAVE AN END!?$"
