ISLANDGAME_ORANNA_SSRAIN_Stairs_MapScripts::
	.byte 0


ISLANDGAME_ORANNA_SSRAIN_Stairs_NPC::
# 4 "data/maps/ISLANDGAME_ORANNA_SSRAIN_Stairs/scripts.pory"
	lock
# 5 "data/maps/ISLANDGAME_ORANNA_SSRAIN_Stairs/scripts.pory"
	faceplayer
# 6 "data/maps/ISLANDGAME_ORANNA_SSRAIN_Stairs/scripts.pory"
	msgbox ISLANDGAME_ORANNA_SSRAIN_Stairs_NPC_Text_0
# 9 "data/maps/ISLANDGAME_ORANNA_SSRAIN_Stairs/scripts.pory"
	release
	return


ISLANDGAME_ORANNA_SSRAIN_Stairs_NPC_Text_0:
# 7 "data/maps/ISLANDGAME_ORANNA_SSRAIN_Stairs/scripts.pory"
	.string "My mom is taking me to the beach later!$"
