ISLANDGAME_AETHERIA_CONDO_2F_MapScripts::
	.byte 0


ISLANDGAME_AETHERIA_CONDO_2F_Man::
# 7 "data/maps/ISLANDGAME_AETHERIA_CONDO_2F/scripts.pory"
	lock
# 8 "data/maps/ISLANDGAME_AETHERIA_CONDO_2F/scripts.pory"
	faceplayer
# 9 "data/maps/ISLANDGAME_AETHERIA_CONDO_2F/scripts.pory"
	msgbox ISLANDGAME_AETHERIA_CONDO_2F_Man_Text_0, MSGBOX_AUTOCLOSE
	return


ISLANDGAME_AETHERIA_CONDO_2F_Man_Text_0:
# 10 "data/maps/ISLANDGAME_AETHERIA_CONDO_2F/scripts.pory"
	.string "This building is always packed to the\n"
	.string "brim in the summertime.\p"
	.string "For tourists, it's the perfect home\n"
	.string "away from home.$"
