ISLANDGAME_CAMP_PERSI_LODGE_2_2F_MapScripts::
	.byte 0


ISLANDGAME_CAMP_PERSI_LODGE_2_2F_Interact_Girl::
# 6 "data/maps/ISLANDGAME_CAMP_PERSI_LODGE_2_2F/scripts.pory"
	msgbox ISLANDGAME_CAMP_PERSI_LODGE_2_2F_Interact_Girl_Text_0, MSGBOX_NPC
	return


ISLANDGAME_CAMP_PERSI_LODGE_2_2F_Interact_Girl_Text_0:
# 7 "data/maps/ISLANDGAME_CAMP_PERSI_LODGE_2_2F/scripts.pory"
	.string "Weeeeeeeeeeeeeeeeeeeeeeeeeeee!!\p"
	.string "Sowwy, I had a lot of sugar today.$"
